# 1、基础站点信息
title: Bufan's Digital Garden
email: plevantem@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
      Intersection of Design, AI and Life.
      Since 2024/1/3.
url: "https://plevantem.github.io/bufan.blog" # the base hostname & protocol for your site, e.g. http://example.com

## Profile
twitter_username: BufanDeng
github_username:  Bufan Deng
avatar: assets/memoji.png
location: Shenzhen, CN
show_excerpts: true

theme_dir: ./_themes/hamilton

# 2、内容配置
posts:
  path: _posts
  layout: post
  excerpt_separator: "<!--more-->" 
paginate: 5
paginate_path: "/page:num/"

# 3、插件配置
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

exclude:
  - README.md
  - vendor/  # 排除依赖安装目录
  - Gemfile
  - Gemfile.lock
  - node_modules/  # 若有其他依赖目录也可一并排除
